[package]
name = "solana-calculator"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.9.4"
thiserror = "1.0.24"
borsh = "0.10.3"

[lib]
crate-type = ["cdylib", "lib"]
